
services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: Poshika@10
      MYSQL_DATABASE: springdb

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: course-container

    depends_on:
      - mysql

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Poshika@10

volumes:
  mysql_data: