version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Poshika@10
      MYSQL_DATABASE: springdb

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pPoshika@10"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    image: rakshithamr10/course-app:latest
    container_name: course-container

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Poshika@10

volumes:
  mysql_data:
